import { app, BrowserWindow } from 'electron';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function createWindow() {
    const win = new BrowserWindow({
        width: 1280,
        height: 720,
        backgroundColor: '#000000',
        useContentSize: true,
        webPreferences: {
            nodeIntegration: false,
            contextIsolation: true
        }
    });

    // Directly grab the index assets generated by the 'build:app' compiler sequence
    win.loadFile(path.join(__dirname, 'dist', 'index.html'));
    win.removeMenu(); // Erases top taskbars for full visual gaming scaling
}

app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') app.quit();
});

